version: '3'
services:
  lb:
    container_name: balancer
    image: dockercloud/haproxy:1.6.3
    environment:
      STATS_AUTH: 'admin:12345678'
      STATS_PORT: '1936'
      MONITOR_PORT: '80'
      MONITOR_URI: '/status'
      ADDITIONAL_SERVICES:
        facebook-leads:backend,
        custom-project:backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
      - 1936:1936

networks:
  default:
    external:
      name: $DOCKER_NETWORK
